defaults: &defaults
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  pool: 12

development:
  <<: *defaults
  database: passport_development

production:
  <<: *defaults
  database: passport_production

test: &test
  <<: *defaults
  database: passport_test
